# Specify our container base image
FROM python:3.9

# Select a working directory within our container
WORKDIR /TestDB

# Copy everything from our project root into our WORK DIRECTORY directory
COPY requirements.txt .

COPY . /data

# Install dependencies
RUN pip install -r requirements.txt

COPY . .

# Expose a port
EXPOSE 80

# Execute this command on start
ENTRYPOINT ["python", "SQL.db.py"]